### ISSUE TITLE
Definición de end points

### ISSUE THREAD

**Issue by ManuPerezDev** [fullstacktf/ControlHorarios-Backend#11]

**Comment by ManuPerezDev** [comment]
@yodra Hemos añadido nuevos end-points. Si puedes echarles un ojo y darnos feedback sería fantástico

**Comment by yodra** [comment]
@Pandacore Sorry acabo de ver el mensaje, donde puede ver los endpoints?

**Comment by arianezf** [comment]
Buenos días! Los endpoints están definidos en el README del Backend.

**Comment by yodra** [comment]
😕 vale estan en la rama `dev` intenten poner enlace a este tipo de cosas cuando alguien no lo encuentra, como tip 😉.

Respecto a los `endpoints`:

Podemos definirlos de varias formas, como ejemplo, si voy a fichar la entrada podría tener dos opciones:
1. Algo similar a`/api/fichajes/entrada` (en ingles claro, solo pongo a modo de ejemplo) Y esto en el body llevaría la hora y el id del empleado
2. O algo así `/api/employees/{employeeId}/entrada` Y en el body solo iría la hora de entrada

Dicho esto tengo algunas dudas:
1. `/api/company/holidays/{id}` La idea es poder poner un día de vacaciones? intenten especificar que llevaría el body para que el README sirva como documentación del API.
2. `/api/employee/checkin/{id}` No me queda claro el `id` que pasan por el path al final de este endpoint, se refiere al del empleado? de ser asi debería ir pegado a empleado.
3. Los endpoints normalmente los he visto en plural, ejemplo: `/api/employees`
4. `/api/company/settings/{id}` No tengo claro que podemos modificar o consultar aquí, quizás es por que me falta la info del body.

Cualquier cosa me dicen y comentamos 🙂

**Comment by ManuPerezDev** [comment]
Muchas gracias por el feedback Yodra. Hemos dado una vueltilla más de tuerca a los end-point teniendo en cuenta lo que comentas. Creo que ahora se ajustan más a lo que buscamos y también hemos añadido la información que contiene el body. Aunque es bastante preeliminar creo que vamos por buen camino. 😄
